"""empty message

Revision ID: 27adf18866cb
Revises: 7691ce90d445
Create Date: 2025-03-15 15:20:44.891236

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '27adf18866cb'
down_revision = '7691ce90d445'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_profiles', schema=None) as batch_op:
        batch_op.drop_column('password')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_profiles', schema=None) as batch_op:
        batch_op.add_column(sa.Column('password', sa.VARCHAR(length=128), autoincrement=False, nullable=True))

    # ### end Alembic commands ###
